export const GET_DOCTOR_REQUEST = 'GET_DOCTOR_REQUEST'; 
export const GET_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS'; 
export const GET_DOCTOR_FAIL = 'GET_DOCTOR_FAIL'; 



//doctor CREATE  profile 

export const  POST_DOCTOR_PROFILE='POST_DOCTOR_PROFILE';
export const  POST_DOCTOR_PROFILE_SUCCESS='POST_DOCTOR_PROFILE_SUCCESS';
export const  POST_DOCTOR_PROFILE_FAIL='POST_DOCTOR_PROFILE_FAIL';